### ISSUE TITLE
Last.fm not working

### ISSUE THREAD

**Issue by dolivo** [gqgs/3x3-generator#273]
Last.fm album covers are not loading

**Comment by gqgs** [comment]
@dolivo Hello. Thanks for the report. Is it still broken for you? Seems to be working fine in some tests I did.

![image](https://github.com/gqgs/3x3-generator/assets/32180229/27afa51a-14fa-4c1b-8790-9f682d5fcdb4)

**Comment by gqgs** [comment]
Closing this since we haven't been provided steps for a reproduction.
Feel free to reopen with the reproduction steps if it's still an issue.
