### ISSUE TITLE
Doma

### ISSUE THREAD

**Issue by Ignaadex** [gqgs/3x3-generator#6]
Doma from Demon Slayer is missing, i'm new, can i help with something?

**Comment by gqgs** [comment]
Hi @Ignaadex. Thanks for the issue.
Kitsu and Minako don't seem to have him for some reason but he's available in Jikan and Anilist as "Douma".

![douma](https://user-images.githubusercontent.com/32180229/162028955-6021f219-76c8-4c72-a446-1d03a89ef63b.png)

If you seen any way we can improve the results in our side feel free to suggest it or open a PR.

**Comment by gqgs** [comment]
I don't think there is anything else actionable that we can do it in our side here.
For the missing sites the character should be available after someone submits him to the respective site.
